### ISSUE TITLE
The CreateImportFiles does not limit stocks to valid stocks in the base period

### ISSUE THREAD

**Issue by nick-komick** [PSC-CoTC/PSC-FRAM-Admin#6]
The PersonFramStocks includes definitions for the following stocks that are not in the base period:

Area 9 Miscellaneous Wild UnMarked (121)
Area 9 Miscellaneous Wild Marked (122)
Makah Coastal Wild UnMarked (123)
Makah Coastal Wild Marked (124)

These should be excluded when creating import files.

**Comment by methiess** [comment]
"person.name" changed to blank for these stocks (121, 122, 123, 124) in the PersonFramStocks.csv file
